# Generated by Django 4.1.7 on 2023-03-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CarBodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузова',
            },
        ),
        migrations.CreateModel(
            name='CarCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='Линейка')),
                ('engine_type', models.CharField(choices=[('Дизель', 'Дизель'), ('Бензин', 'Бензин'), ('Газ', 'Газ'), ('Электро', 'Электро'), ('Гибрид', 'Гибрид')], db_index=True, max_length=15, verbose_name='Тип двигателя')),
                ('engine_volume', models.FloatField(verbose_name='Объем двигателя')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('length', models.PositiveIntegerField(verbose_name='Длина')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Цвет машины')),
            ],
            options={
                'verbose_name': 'Цвет автомобиля',
                'verbose_name_plural': 'Цвета автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Произодитель')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(db_index=True, max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('document_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Номер удостоверения')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('cars', models.ManyToManyField(related_name='car', to='taxi.car', verbose_name='Автомобили')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(db_index=True, max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_flight', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('address_from', models.CharField(max_length=255, verbose_name='Откуда')),
                ('address_to', models.CharField(max_length=255, verbose_name='Куда')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.driver', verbose_name='Водитель')),
                ('passenger', models.ManyToManyField(related_name='passenger', to='taxi.passenger', verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.carbodytype', verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='car',
            name='characteristics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.carcharacteristic', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.carcolor', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='car',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.carmanufacturer', verbose_name='Марка'),
        ),
    ]
