# Generated by Django 4.1.7 on 2023-03-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcharacteristic',
            name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=60, verbose_name='Линейка'),
            preserve_default=False,
        ),
    ]
