# Generated by Django 4.1.7 on 2023-03-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_remove_carcharacteristic_name_car_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbodytype',
            old_name='name',
            new_name='body_type',
        ),
    ]
